# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('delka', models.CharField(max_length=10)),
                ('sirka', models.CharField(max_length=10)),
                ('up', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
