# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sledovani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='delka',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='rider',
            name='sirka',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='rider',
            name='up',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
