# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sledovani', '0002_auto_20170130_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sledovani.Rider'),
        ),
    ]
